### PR TITLE
Issue 5

### PR DESCRIPTION
**Pull request by kbknapp**
I haven't fully tested this... but it's also a difficult thing to test :P

### CODE REVIEW

**Comment by cburgdorf** [comment]
Looks good :+1:

**Comment by kbknapp** [comment]
Just tested, and it's good to go. There were a few bugs in the last one, but they're gone! :+1:

**Comment by kbknapp** [comment]
Once this merges, I recommend we release another version on crates.io and update clog-cli and release to crates.io as well since `cargo install` is a thing now.

**Comment by cburgdorf** [comment]
Thanks! I noticed that since we split up cli and lib we haven't had a tag for the lib but had a published version `0.8.2`. In order to append to the changelog correctly I had to pick a commit and mark it as `0.8.2`. I hope I picked the right one but even if not that shouldn't really hurt anyone I think.

**Comment by cburgdorf** [comment]
I also published a version `0.9.1` of the CLI on crates.io and tested the `cargo install` command. You need a nightly of Rust to use that command but it works fine :+1:

**Pull request merged**
