### PR TITLE
Add dependencies tree to README.md

### PR DESCRIPTION
**Pull request by Vinatorul**
Nice to have, I think :)

### CODE REVIEW

**Comment by kbknapp** [comment]
I like these (as you can see from my repos :smile:). Thoughts @cburgdorf ?

**Comment by Vinatorul** [comment]
@kbknapp @cburgdorf if you will like it -> I'm ready to create PR to clog-cli

**Comment by kbknapp** [comment]
I would assume whatever decision is made here will apply there as well ;)

**Comment by cburgdorf** [comment]
I'm not terrible excited but I'm also not really against it. But then, I'm the last person you want to ask when it comes to good Readme files ;) I'd ask @PascalPrecht what he thinks ;)

**Comment by PascalPrecht** [comment]
Not sure if this adds value to the project. Especially considering the fact that dependencies change too often. I don't think we want to maintain this asset then.

**Comment by cburgdorf** [comment]
I agree on the maintainability aspect. On a second thought, I'd rather vote against it. Sorry :-/

**Comment by Vinatorul** [comment]
No problem, that takes about one minute to do.

**Pull request closed without merging**
